enum TipoUsuario { CLIENTE, TRABAJADOR }

enum TipoTrabajador { ADMIN, RECEPCIONISTA, INSTRUCTOR }

enum Dia { LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO }

enum EstadoPago { PENDIENTE, COMPLETADO, CANCELADO }


